language: node_js
node_js:
  - "6"
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run serve:webpack
  - yarn run serve:browserify
  - yarn run test:store
